version: '1.1'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3000
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      -  test-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: emotion_assistant_system
      MYSQL_ROOT_PASSWORD: guang
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - test-redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
volumes:
  test-mysql:
    external: true
  test-redis:
    external: true

